name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Draft Boxed.AspNetCore Release"
        uses: release-drafter/release-drafter@v5.24.0
        with:
          config-name: "release-drafter-Boxed.AspNetCore.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Draft Boxed.DotnetNewTest Release"
        uses: release-drafter/release-drafter@v5.24.0
        with:
          config-name: "release-drafter-Boxed.DotnetNewTest.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Draft Boxed.Mapping Release"
        uses: release-drafter/release-drafter@v5.24.0
        with:
          config-name: "release-drafter-Boxed.Mapping.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
